---
version: '3'
tasks:
  build:
    sources:
      - cli/**/*.go
      - share/**/*.go
    generates:
      - nvb
      - nvl
    env:
      CGO_ENABLED: 0
      GOOS: linux
    cmds:
      - go build -ldflags="-s -w" -o nvb ./cli/nvb/
      - go build -ldflags="-s -w" -o nvl ./cli/nvl/
  install:
    deps: [build]
    cmds:
      - sudo cp nvb /usr/bin/nvb
      - sudo cp nvl /usr/bin/nvl
      - chmod +x ~/.local/bin/nv{l,b}
